server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 19981119
    driver-class-name: com.mysql.jdbc.Driver
#      discovery:
#        cluster-name: HZ
  application:
    name: user-service
    profiles:
      active: dev # 环境
    cloud:
      nacos:
        server-addr: http://10.173.42.57:8848 # nacos地址
        config:
          file-extension: yaml # 文件后缀名
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true
  # 添加客户端配置
  client:
    config:
      default:
        connectTimeout: 3000    # 连接超时3秒
        readTimeout: 3000       # 读取超时3秒
